ALTER TYPE public.notification_type ADD VALUE IF NOT EXISTS 'CO_WITHDRAWN';
ALTER TYPE public.notification_type ADD VALUE IF NOT EXISTS 'BACKCHARGE_CREATED';
ALTER TYPE public.notification_type ADD VALUE IF NOT EXISTS 'RETAINAGE_RELEASED';