CREATE OR REPLACE VIEW public.change_orders_role_view
WITH (security_invoker = on) AS
SELECT id,
    org_id,
    project_id,
    created_by_user_id,
    created_by_role,
    co_number,
    title,
    status,
    pricing_type,
    CASE WHEN co_viewer_role(id) = ANY (ARRAY['gc'::text,'tc'::text,'fc'::text]) THEN nte_cap ELSE NULL::numeric END AS nte_cap,
    CASE WHEN co_viewer_role(id) = ANY (ARRAY['gc'::text,'tc'::text,'fc'::text]) THEN nte_increase_requested ELSE NULL::numeric END AS nte_increase_requested,
    nte_increase_approved,
    reason,
    reason_note,
    location_tag,
    assigned_to_org_id,
    fc_input_needed,
    materials_needed,
    materials_on_site,
    equipment_needed,
    materials_responsible,
    equipment_responsible,
    shared_at,
    combined_at,
    combined_co_id,
    parent_co_id,
    submitted_at,
    approved_at,
    rejected_at,
    rejection_note,
    contracted_at,
    draft_shared_with_next,
    created_at,
    updated_at,
    use_fc_pricing_base,
    closed_for_pricing_at,
    completed_at,
    completion_acknowledged_at,
    CASE WHEN co_viewer_role(id) = ANY (ARRAY['gc'::text,'tc'::text]) THEN tc_snapshot_hourly_rate ELSE NULL::numeric END AS tc_snapshot_hourly_rate,
    CASE WHEN co_viewer_role(id) = 'tc'::text THEN tc_snapshot_markup_percent ELSE NULL::numeric END AS tc_snapshot_markup_percent,
    CASE WHEN co_viewer_role(id) = ANY (ARRAY['gc'::text,'tc'::text]) THEN tc_submitted_price ELSE NULL::numeric END AS tc_submitted_price,
    fc_pricing_submitted_at,
    CASE WHEN co_viewer_role(id) = 'gc'::text THEN gc_budget ELSE NULL::numeric END AS gc_budget,
    co_material_responsible_override,
    co_equipment_responsible_override,
    assembly_state,
    trigger_code,
    document_type,
    withdrawn_at,
    withdrawn_reason,
    tax_rate_snapshot,
    labor_taxable_snapshot,
    CASE WHEN co_viewer_role(id) = ANY (ARRAY['gc'::text,'tc'::text]) THEN materials_tax ELSE NULL::numeric END AS materials_tax,
    CASE WHEN co_viewer_role(id) = ANY (ARRAY['gc'::text,'tc'::text]) THEN labor_tax ELSE NULL::numeric END AS labor_tax,
    CASE WHEN co_viewer_role(id) = ANY (ARRAY['gc'::text,'tc'::text]) THEN equipment_tax ELSE NULL::numeric END AS equipment_tax,
    CASE WHEN co_viewer_role(id) = ANY (ARRAY['gc'::text,'tc'::text]) THEN total_tax ELSE NULL::numeric END AS total_tax,
    owner_approval_status,
    owner_approved_at,
    owner_approver_name,
    owner_rejection_note,
    architect_approval_status,
    architect_approved_at,
    architect_approver_name,
    architect_rejection_note,
    CASE WHEN co_viewer_role(id) = ANY (ARRAY['gc'::text,'tc'::text]) THEN retainage_amount ELSE NULL::numeric END AS retainage_amount,
    retainage_released,
    retainage_released_at,
    blocked_by_rfi_id,
    entry_source,
    problem_summary,
    problem_voice_url,
    ai_intake_id
FROM change_orders co;