ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'NTE_REQUESTED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'NTE_APPROVED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'NTE_REJECTED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'CO_SHARED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'CO_RECALLED';